recaptchaSiteKey: 6LfsnJMeAAAAAK1J8BN0RVt66qtV3EL4-KWqeRWF
workerURL: https://githubissues-dev.ubccsssbot.workers.dev
gcseURL: https://cse.google.com/cse.js?cx=7ec12103dfbe60f4f
CFBeaconData: '{"token": "dummyPrevCFToken"}'
