recaptchaSiteKey: 6LfwnJMeAAAAADc_zi-tMSdI11N9r5TK1M2TOs8v
workerURL: https://githubissues.ubccsssbot.workers.dev
gcseURL: https://cse.google.com/cse.js?cx=055e806dfad34435d
CFBeaconData: '{"token": "4c78fce6acb34b21946886e430f7a528"}'
