name: Prettifier

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_version: "2.8.8"
          prettier_options: --write **/*.+(js|html|css|json|md|yaml|yml)
          prettier_plugins: "prettier-plugin-go-template"
          github_token: ${{ secrets.GH_TOKEN }}
          only_changed: True
